coverage:
  status:
    project:
      default:
        # 전체 커버리지는 기존 대비 최대 5% 감소까지 허용
        threshold: 5
    patch:
      default:
        # 패치 커버리지는 3% 감소까지만 허용
        threshold: 3

comment: false
